### ISSUE TITLE
非域控

### ISSUE THREAD

**Issue by spacexnasa** [qwsddn/autowork#1]
如果是非域控下，该怎么办呢？

**Comment by qwsddn** [comment]
不需要在域控上运行工具，运行工具的机器能连通远程主机的445端口即可，如果是Linux服务器就要能够连通22端口。
如果你指的是非域环境的使用，将远程window主机的凭据加到运行autowork的主机就可以了，具体参考工具的帮助文档1.2章节的功能简介部分。

**Comment by yepinjia** [comment]
请问你们的工具怎么编译生产exe。按照你的文档里面写的执行步骤，缺少addpyenv.ps1文件。

**Comment by xiaoyueraymond** [comment]
@yepinjia 我是新手 ，怎么编译生成exe？

**Comment by qwsddn** [comment]
这个工具用powershell studio编写的，需要用这个powershell studio软件来将powershell代码生成exe文件。

**Comment by qwsddn** [comment]
这个工具用powershell studio编写的，需要用这个powershell studio软件来将powershell代码生成exe文件。要测试或者使用的话可以直接用这个编译好的：https://pan.baidu.com/s/1slocDbf

**Comment by qwsddn** [comment]
这个工具用powershell studio编写的，需要用这个powershell studio软件来将powershell代码生成exe文件。
